export const AJAX_CALL = 'AJAX_CALL';
export const AJAX_CALL_FAILURE = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';

export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';

export const LOAD_HNODE_SUCCESS = 'LOAD_HNODE_SUCCESS';
export const LOAD_HNODE_FAILURE = 'LOAD_HNODE_FAILURE';
export const LOAD_HNODE_UNNECESSARY = 'LOAD_HNODE_UNNECESSARY';
export const LOAD_HNODETYPE_SUCCESS = 'LOAD_HNODETYPE_SUCCESS';
export const LOAD_HNODETYPE_FAILURE = 'LOAD_HNODETYPE_FAILURE';
export const LOAD_HNODETYPE_UNNECESSARY = 'LOAD_HNODETYPE_UNNECESSARY';
export const LOAD_APPCONFIG_SUCCESS = 'LOAD_APPCONFIG_SUCCESS';
export const LOAD_APPCONFIG_FAILURE = 'LOAD_APPCONFIG_FAILURE';
export const LOAD_APPCONFIG_UNNECESSARY = 'LOAD_APPCONFIG_UNNECESSARY';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_UNNECESSARY = 'LOGIN_UNNECESSARY';
export const LOAD_SECURITY_PROFILE_SUCCESS = 'LOAD_SECURITY_PROFILE_SUCCESS';
export const LOAD_SECURITY_USER = 'LOAD_SECURITY_USER';
export const LOAD_SECURITY_USER_SUCCESS = 'LOAD_SECURITY_USER_SUCCESS';
export const GETACTIVERECORD_SECURITY_USER_SUCCESS = 'GETACTIVERECORD_SECURITY_USER_SUCCESS';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_APP_ROUTES = 'SET_APP_ROUTES';
export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
export const ACTIVERECORDVIEWER_SHOW = 'ACTIVERECORDVIEWER_SHOW';
export const ACTIVERECORDVIEWER_HIDE = 'ACTIVERECORDVIEWER_HIDE';
export const DIALOG_OPEN = 'DIALOG_OPEN';
export const DIALOG_CLOSE = 'DIALOG_CLOSE';
export const DETAILPANE_OPEN = 'DETAILPANE_OPEN';
export const DETAILPANE_CLOSE = 'DETAILPANE_CLOSE';
export const CANCEL_SECURITY_USER = 'CANCEL_SECURITY_USER';

export const TAB_GROUP_NEW = 'TAB_GROUP_NEW';
export const TAB_GROUP_EDIT = 'TAB_GROUP_EDIT';
export const TAB_GROUP_CLEAR = 'TAB_GROUP_CLEAR';

export const PW_RESET = 'PW_RESET';
export const PW_RESET_SUCCESS = 'PW_RESET_SUCCESS';
export const PW_RESET_FAILURE = 'PW_RESET_FAILURE';

export const PW_CONFIRMATION_CHANGED = 'PW_CONFIRMATION_CHANGED';

export const TAB_CURRENT_CHANGED = 'TAB_CURRENT_CHANGED'; //not related to TAB_GROUP actions